### Sistema de recomendação com Restricted Boltzmann Machines

Estes são processos de aprendizagem estocásticos com estrutura recorrente e são a base das técnicas de otimização iniciais usadas na RNA. A Boltzmann Machine foi inventada por Geoffrey Hinton e Terry Sejnowski em 1985. 

**Objetivo da Boltzmann Machines:**
O principal objetivo da Boltzmann Machine é otimizar a solução de um problema. O trabalho da Boltzmann Machine é otimizar os pesos e quantidades relacionados a esse problema específico.

**Importações iniciais**

In [13]:
from rbm import RBM
import numpy as np

**Criação da Restricted Boltzmann Machine**

In [14]:
rbm = RBM(num_visible = 6, num_hidden = 2)

**Criação da base de dados**

In [15]:
base = np.array([[1,1,1,0,0,0],
                 [1,0,1,0,0,0],
                 [1,1,1,0,0,0],
                 [0,0,1,1,1,1],
                 [0,0,1,1,0,1],
                 [0,0,1,1,0,1]])


filmes = ["A bruxa", "Invocação do mal", "O chamado",
          "Se beber não case", "Gente grande", "American pie"]

**Treinamento da RBM**

In [16]:
rbm.train(base, max_epochs = 5000)

Epoch 0: error is 9.040194685853999
Epoch 1: error is 8.892031488364443
Epoch 2: error is 8.785596156389468
Epoch 3: error is 8.617566759856429
Epoch 4: error is 8.423347947277307
Epoch 5: error is 8.283745672006434
Epoch 6: error is 8.351325417620814
Epoch 7: error is 8.067402710858627
Epoch 8: error is 8.023951622883468
Epoch 9: error is 7.949819317532327
Epoch 10: error is 7.866582480461666
Epoch 11: error is 7.803025777659471
Epoch 12: error is 7.849487711778961
Epoch 13: error is 7.657327874732611
Epoch 14: error is 7.6381252898319625
Epoch 15: error is 7.490230746577975
Epoch 16: error is 7.49388385673561
Epoch 17: error is 7.3403649633071035
Epoch 18: error is 7.478621759428561
Epoch 19: error is 7.279683950986708
Epoch 20: error is 7.2810600432907675
Epoch 21: error is 7.260176499854646
Epoch 22: error is 7.300096384433622
Epoch 23: error is 7.198576267956037
Epoch 24: error is 7.279086394934013
Epoch 25: error is 7.1399939795851095
Epoch 26: error is 7.265821306996258
Epoch 27

Epoch 379: error is 1.870275990577072
Epoch 380: error is 1.6395222137812016
Epoch 381: error is 1.6306660184139035
Epoch 382: error is 2.6762723599114695
Epoch 383: error is 1.8386313588930485
Epoch 384: error is 1.6040788819597918
Epoch 385: error is 2.3617679098090996
Epoch 386: error is 1.5875829207649605
Epoch 387: error is 1.5795202214792565
Epoch 388: error is 2.115585631630634
Epoch 389: error is 1.80043086364533
Epoch 390: error is 2.0895680351978347
Epoch 391: error is 1.78427198195285
Epoch 392: error is 1.7773918508915554
Epoch 393: error is 1.5375222583009782
Epoch 394: error is 1.765337155661793
Epoch 395: error is 1.5253749524434823
Epoch 396: error is 2.3275728739322923
Epoch 397: error is 2.619393279503344
Epoch 398: error is 2.3191104436251986
Epoch 399: error is 1.494603387208007
Epoch 400: error is 2.0678345994709364
Epoch 401: error is 1.7293443124141001
Epoch 402: error is 2.2615970489208057
Epoch 403: error is 1.470739144394983
Epoch 404: error is 2.2469016774765

Epoch 1111: error is 1.3528780290588862
Epoch 1112: error is 1.3525259041748052
Epoch 1113: error is 0.9757166845096473
Epoch 1114: error is 1.3531801297624293
Epoch 1115: error is 0.972357714948208
Epoch 1116: error is 1.3538363396946853
Epoch 1117: error is 1.3534423707097598
Epoch 1118: error is 1.35306295851847
Epoch 1119: error is 1.3526976046797914
Epoch 1120: error is 1.3523458241406259
Epoch 1121: error is 1.3520071451370408
Epoch 1122: error is 1.3516811090750296
Epoch 1123: error is 1.3513672703926607
Epoch 1124: error is 1.3510651964054092
Epoch 1125: error is 0.979067605467004
Epoch 1126: error is 1.3517148645717847
Epoch 1127: error is 1.3513963978327057
Epoch 1128: error is 1.3510898681203474
Epoch 1129: error is 1.3507948504389606
Epoch 1130: error is 0.9790427946697948
Epoch 1131: error is 1.3514442340577648
Epoch 1132: error is 1.3511325634760079
Epoch 1133: error is 1.3508325962881909
Epoch 1134: error is 1.3505439144625528
Epoch 1135: error is 1.3502661124516768
Epoc

Epoch 1960: error is 0.7790215032756483
Epoch 1961: error is 0.7777249376569004
Epoch 1962: error is 0.776462629250522
Epoch 1963: error is 2.314220380554725
Epoch 1964: error is 1.4085426517735187
Epoch 1965: error is 1.4064840251253121
Epoch 1966: error is 0.7771981759627712
Epoch 1967: error is 1.4058861588517573
Epoch 1968: error is 1.4038836409908897
Epoch 1969: error is 0.7791400565436403
Epoch 1970: error is 1.4033615126434416
Epoch 1971: error is 1.4014140208318864
Epoch 1972: error is 0.7810549938780184
Epoch 1973: error is 1.4009644481209609
Epoch 1974: error is 1.399070766088893
Epoch 1975: error is 0.782939293476061
Epoch 1976: error is 0.7814995821298406
Epoch 1977: error is 0.780098975115421
Epoch 1978: error is 1.4016027511130622
Epoch 1979: error is 1.3996952629030524
Epoch 1980: error is 1.397831208999091
Epoch 1981: error is 1.3960105227355153
Epoch 1982: error is 0.785293998663221
Epoch 1983: error is 1.3957224667055026
Epoch 1984: error is 0.7854281006888865
Epoch 1

Epoch 2827: error is 0.6935154131888144
Epoch 2828: error is 0.6934250030907909
Epoch 2829: error is 0.6933357051738125
Epoch 2830: error is 0.6932475004470258
Epoch 2831: error is 0.6931603703025087
Epoch 2832: error is 0.6930742965062469
Epoch 2833: error is 0.6929892611893563
Epoch 2834: error is 0.6929052468395428
Epoch 2835: error is 0.6928222362927934
Epoch 2836: error is 0.6927402127252907
Epoch 2837: error is 0.6926591596455441
Epoch 2838: error is 0.6925790608867313
Epoch 2839: error is 0.6924999005992439
Epoch 2840: error is 0.6924216632434308
Epoch 2841: error is 1.536527151873752
Epoch 2842: error is 0.6927968078074417
Epoch 2843: error is 0.692713361450306
Epoch 2844: error is 0.6926309107104213
Epoch 2845: error is 1.5349272307082402
Epoch 2846: error is 1.5321372405832743
Epoch 2847: error is 0.6935188317605813
Epoch 2848: error is 0.6934231553030817
Epoch 2849: error is 1.5301926232453131
Epoch 2850: error is 0.6938488725349844
Epoch 2851: error is 0.6937473506058597
Ep

Epoch 3651: error is 0.6791999635695454
Epoch 3652: error is 0.6791793973881679
Epoch 3653: error is 0.6791589752580827
Epoch 3654: error is 0.679138695590697
Epoch 3655: error is 0.6791185568178827
Epoch 3656: error is 0.6790985573916699
Epoch 3657: error is 0.6790786957839476
Epoch 3658: error is 0.6790589704861675
Epoch 3659: error is 0.6790393800090552
Epoch 3660: error is 1.5802836600149046
Epoch 3661: error is 0.6792102082606304
Epoch 3662: error is 0.6791888664957457
Epoch 3663: error is 0.6791676780167533
Epoch 3664: error is 0.6791466411182321
Epoch 3665: error is 0.6791257541169625
Epoch 3666: error is 0.6791050153515893
Epoch 3667: error is 0.6790844231822909
Epoch 3668: error is 0.6790639759904548
Epoch 3669: error is 0.6790436721783583
Epoch 3670: error is 0.6790235101688558
Epoch 3671: error is 0.6790034884050701
Epoch 3672: error is 0.6789836053500917
Epoch 3673: error is 0.6789638594866795
Epoch 3674: error is 0.6789442493169716
Epoch 3675: error is 0.6789247733621967
E

Epoch 4427: error is 0.6740173717451843
Epoch 4428: error is 0.6740108745499371
Epoch 4429: error is 1.6049628609125948
Epoch 4430: error is 0.6740850793321437
Epoch 4431: error is 0.6740779793932521
Epoch 4432: error is 0.6740709092036433
Epoch 4433: error is 0.6740638685353794
Epoch 4434: error is 0.6740568571624875
Epoch 4435: error is 0.6740498748609409
Epoch 4436: error is 0.6740429214086404
Epoch 4437: error is 0.6740359965853958
Epoch 4438: error is 0.6740291001729082
Epoch 4439: error is 0.6740222319547516
Epoch 4440: error is 0.6740153917163564
Epoch 4441: error is 1.6040680122849964
Epoch 4442: error is 0.6740957977911074
Epoch 4443: error is 0.6740883096893152
Epoch 4444: error is 0.6740808548029005
Epoch 4445: error is 0.6740734328727733
Epoch 4446: error is 0.674066043642125
Epoch 4447: error is 0.6740586868564056
Epoch 4448: error is 0.674051362263301
Epoch 4449: error is 1.621364910533774
Epoch 4450: error is 0.6739467088483099
Epoch 4451: error is 0.6739401770322557
Epo

**Visualização dos pesos**

In [17]:
rbm.weights

array([[ 2.46236148,  2.32240043,  0.40708347],
       [-0.9638892 , -3.3044384 ,  7.89716046],
       [ 0.2001923 , -7.20735399,  3.28986972],
       [ 4.94516524,  3.90591739,  1.90326936],
       [ 0.89309354,  3.66662013, -8.19673513],
       [-1.33817309,  0.63312507, -4.53458466],
       [ 0.89866266,  3.66230554, -8.19939579]])

**Análise de acordo com os usuários**

In [18]:
usuario1 = np.array([[1,1,0,1,0,0]])
usuario2 = np.array([[0,0,0,1,1,0]])


rbm.run_visible(usuario1)
rbm.run_visible(usuario2)

array([[1., 0.]])

In [19]:
camada_escondida = np.array([[1,0]])
recomendacao = rbm.run_hidden(camada_escondida)
recomendacao

array([[0., 0., 1., 1., 0., 1.]])

In [ ]:
for i in range(len(usuario1[0])):
    if usuario1[0,i] == 0 and recomendacao[0,i] =

**Referências**

https://translate.google.com/translate?hl=pt-BR&sl=en&u=https://www.tutorialspoint.com/artificial_neural_network/artificial_neural_network_boltzmann_machine.htm&prev=search&pto=aue

https://github.com/echen/restricted-boltzmann-machines